### ISSUE TITLE
v1.0.0 does not exists on pub.dev

### ISSUE THREAD

**Issue by AlexV525** [kuloud/amap_map_extensions#1]
![image](https://github.com/user-attachments/assets/54ce2495-cb99-43de-b04b-5209a5506429)

**Comment by kuloud** [comment]
> ![image](https://private-user-images.githubusercontent.com/15884415/360918474-54ce2495-cb99-43de-b04b-5209a5506429.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ0NjIwNDIsIm5iZiI6MTcyNDQ2MTc0MiwicGF0aCI6Ii8xNTg4NDQxNS8zNjA5MTg0NzQtNTRjZTI0OTUtY2I5OS00M2RlLWIwNGItNTIwOWE1NTA2NDI5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODI0VDAxMDkwMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWJkMTM5YmY2OTVhZmI4ZDFiMTU2MWU5Y2U2ZTAzYWEwYTVkMzNhMzdjMzVmZjk3NzRiNTRlY2YxNjNlYjAzMDkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.r-rvr29ZqqMOwW0DKVgjGYW9-wDYuE19RV8Pg5UdMJc)

对的，只发布了那一个版本，最初是考虑插件接口和SDK对齐（fork的原插件，有些接口放的位置不合理）；基于SDK的功能预留拓展槽，但是后面想加新功能时，发现设计不合理：
1. 大部分需要拓展的能力是基于地图接口的上层业务拓展，拓展相当于做了一个SDK和业务实现的Bridge，对开发实现来说并不友好
2. mapController 作为核心控制类，extensions也只是根据需要获取它进行交互，并不能模块化拆解SDK的依赖模块，增加了多项目的维护成本

**Comment by AlexV525** [comment]
这么说考虑 discontinued 了，不过 map 那边的能力也需要恢复下
