### ISSUE TITLE
使用 extension 无法获取审核号，但直接通过 AMapController 的 channel 手动调用可以拿到

### ISSUE THREAD

**Issue by AlexV525** [kuloud/amap_map_extensions#2]
无效的调用：
```dart
final extensions = AMapMapExtensions();
final number = await extensions.getMapContentApprovalNumber();
print(number);
```

实际有效的调用：
```dart
final number = await controller.channel.invokeMethod('map#contentApprovalNumber');
print(number);
```

**Comment by kuloud** [comment]
> ```dart
> contentApprovalNumber
> ```

<img width="637" alt="image" src="https://github.com/user-attachments/assets/5400e752-5caf-478e-8565-bf4c76fc9951">
extension 需要注入到AMapWidget，并在onMapCreated后使用，并且extensions 机制我是考虑拿掉的，没有多少需要手动拓展的能力
